import { useState } from 'react';
import Sidebar from '@/components/Sidebar';
import Dashboard from '@/components/Dashboard';
import DataUpload from '@/components/DataUpload';
import DataAnalytics from '@/components/DataAnalytics';

const Index = () => {
  const [activeTab, setActiveTab] = useState('dashboard');

  const renderContent = () => {
    switch (activeTab) {
      case 'dashboard':
        return <Dashboard />;
      case 'upload':
        return <DataUpload />;
      case 'analytics':
        return <DataAnalytics />;
      case 'datasets':
        return (
          <div className="animate-fade-in">
            <h1 className="text-3xl font-bold gradient-text mb-4">Datasets</h1>
            <p className="text-muted-foreground">Manage your uploaded datasets and their schemas.</p>
          </div>
        );
      case 'insights':
        return (
          <div className="animate-fade-in">
            <h1 className="text-3xl font-bold gradient-text mb-4">AI Insights</h1>
            <p className="text-muted-foreground">Discover patterns and insights generated by AI analysis.</p>
          </div>
        );
      case 'reports':
        return (
          <div className="animate-fade-in">
            <h1 className="text-3xl font-bold gradient-text mb-4">Reports</h1>
            <p className="text-muted-foreground">View and download your generated reports.</p>
          </div>
        );
      case 'settings':
        return (
          <div className="animate-fade-in">
            <h1 className="text-3xl font-bold gradient-text mb-4">Settings</h1>
            <p className="text-muted-foreground">Configure your dashboard preferences and API settings.</p>
          </div>
        );
      default:
        return <Dashboard />;
    }
  };

  return (
    <div className="flex h-screen bg-background">
      <Sidebar activeTab={activeTab} onTabChange={setActiveTab} />
      <main className="flex-1 overflow-auto">
        <div className="p-8">
          {renderContent()}
        </div>
      </main>
    </div>
  );
};

export default Index;
