
import { useState } from 'react';
import Sidebar from '@/components/Sidebar';
import Dashboard from '@/components/Dashboard';
import DataUpload from '@/components/DataUpload';
import DataAnalytics from '@/components/DataAnalytics';

const Index = () => {
  const [activeTab, setActiveTab] = useState('dashboard');

  const renderContent = () => {
    switch (activeTab) {
      case 'dashboard':
        return <Dashboard />;
      case 'upload':
        return <DataUpload />;
      case 'analytics':
        return <DataAnalytics />;
      case 'datasets':
        return (
          <div className="animate-fade-in space-y-6">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold text-foreground">Datasets</h1>
              <p className="text-muted-foreground text-lg">Manage your uploaded datasets and their schemas.</p>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Available Datasets</h3>
                <p className="text-muted-foreground">View and manage all your uploaded data files</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Schema Management</h3>
                <p className="text-muted-foreground">Define and modify data structures and relationships</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Data Quality</h3>
                <p className="text-muted-foreground">Monitor data integrity and validation status</p>
              </div>
            </div>
          </div>
        );
      case 'insights':
        return (
          <div className="animate-fade-in space-y-6">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold text-foreground">AI Insights</h1>
              <p className="text-muted-foreground text-lg">Discover patterns and insights generated by AI analysis.</p>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Predictive Analytics</h3>
                <p className="text-muted-foreground">AI-powered predictions and forecasting models</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Pattern Recognition</h3>
                <p className="text-muted-foreground">Automated discovery of trends and anomalies</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Smart Recommendations</h3>
                <p className="text-muted-foreground">Data-driven suggestions for business optimization</p>
              </div>
            </div>
          </div>
        );
      case 'reports':
        return (
          <div className="animate-fade-in space-y-6">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold text-foreground">Reports</h1>
              <p className="text-muted-foreground text-lg">View and download your generated reports.</p>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Executive Reports</h3>
                <p className="text-muted-foreground">High-level business summaries and KPI dashboards</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Technical Analysis</h3>
                <p className="text-muted-foreground">Detailed data analysis and statistical reports</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Custom Reports</h3>
                <p className="text-muted-foreground">Personalized reports based on your specific needs</p>
              </div>
            </div>
          </div>
        );
      case 'settings':
        return (
          <div className="animate-fade-in space-y-6">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold text-foreground">Settings</h1>
              <p className="text-muted-foreground text-lg">Configure your dashboard preferences and API settings.</p>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">User Preferences</h3>
                <p className="text-muted-foreground">Customize your dashboard layout and theme settings</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">API Configuration</h3>
                <p className="text-muted-foreground">Manage external integrations and API connections</p>
              </div>
              <div className="insight-card">
                <h3 className="text-xl font-semibold text-card-foreground mb-2">Security Settings</h3>
                <p className="text-muted-foreground">Control access permissions and authentication options</p>
              </div>
            </div>
          </div>
        );
      default:
        return <Dashboard />;
    }
  };

  return (
    <div className="flex h-screen bg-background">
      <Sidebar activeTab={activeTab} onTabChange={setActiveTab} />
      <main className="flex-1 overflow-auto">
        <div className="p-8">
          {renderContent()}
        </div>
      </main>
    </div>
  );
};

export default Index;
